### ISSUE TITLE
conflict with webmock

### ISSUE THREAD

**Issue by rweng** [saucelabs/sauce_ruby#150]
Hi,

I am getting the following exception

```
.rvm/gems/ruby-2.0.0-p0/gems/net-http-persistent-2.8/lib/net/http/persistent.rb:959:in `rescue in request': too many connection resets (due to HTTP session not yet started - IOError) after 0 requests on 70311282677420, last used 1372837005.051968 seconds ago (Net::HTTP::Persistent::Error)
    from /Users/robin/.rvm/gems/ruby-2.0.0-p0/gems/net-http-persistent-2.8/lib/net/http/persistent.rb:968:in `request'
    from /Users/robin/.rvm/gems/ruby-2.0.0-p0/gems/selenium-webdriver-2.31.0/lib/selenium/webdriver/remote/http/persistent.rb:31:in `response_for'
    from /Users/robin/.rvm/gems/ruby-2.0.0-p0/gems/selenium-webdriver-2.31.0/lib/selenium/webdriver/remote/http/default.rb:39:in `request'
    from /Users/robin/.rvm/gems/ruby-2.0.0-p0/gems/selenium-webdriver-2.31.0/lib/selenium/webdriver/remote/http/common.rb:40:in `call'
    from /Users/robin/.rvm/gems/ruby-2.0.0-p0/gems/selenium-webdriver-2.31.0/lib/selenium/webdriver/remote/bridge.rb:616:in `raw_execute'
    from /Users/robin/.rvm/gems/ruby-2.0.0-p0/gems/selenium-webdriver-2.31.0/lib/selenium/webdriver/remote/bridge.rb:594:in `execute'
    from /Users/robin/.rvm/gems/ruby-2.0.0-p0/gems/selenium-webdriver-2.31.0/lib/selenium/webdriver/remote/bridge.rb:190:in `quit'
    from /Users/robin/.rvm/gems/ruby-2.0.0-p0/gems/selenium-webdriver-2.31.0/lib/selenium/webdriver/common/driver.rb:168:in `quit'
    from /Users/robin/.rvm/gems/ruby-2.0.0-p0/gems/sauce-3.0.4/lib/sauce/selenium.rb:41:in `method_missing'
    from /Users/robin/.rvm/gems/ruby-2.0.0-p0/gems/sauce-3.0.4/lib/sauce/capybara.rb:110:in `finish!'
    from /Users/robin/.rvm/gems/ruby-2.0.0-p0/gems/sauce-3.0.4/lib/sauce/capybara.rb:85:in `block in browser'
```

I tracked it down to a conflict in WebMock: https://github.com/bblimke/webmock/issues/208

However, since VCR/WebMock is quite common I thought I'll let you know. Maybe you could help investigating. If not, feel free to close.

Thanks,
Robin

**Comment by nvreynolds** [comment]
thanks for the thread! :+1:
